apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiddu-proj
  labels:
    app: kiddu-proj
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kiddu-proj
  template:
    metadata:
      labels:
        app: kiddu-proj
    spec:
      containers:
      - name: kiddu-proj
        image: 020866158197.dkr.ecr.us-east-1.amazonaws.com/kiddu-proj:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "1"
        env:
        - name: CAPSTONE_TEST
          valueFrom:
            secretKeyRef:
              name: capstone-secret
              key: CAPSTONE_TEST

---
apiVersion: v1
kind: Service
metadata:
  name: kiddu-proj-service
spec:
  type: LoadBalancer
  selector:
    app: kiddu-proj
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000